---
inventory_groupname: builders
builder_pkgs:
  - ansible
  - ansible-runner
  - python39-ansible-runner
  - ansible-builder
  - ansible-navigator
  - libguestfs-tools
builder_repos:
  - ansible-2.9-for-rhel-8-x86_64-rpms
  - ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms
builder_github: "https://github.com/syspimp/aap-repo"
