---
inventory_groupname: builders
builder_pkgs:
  - ansible
  - ansible-runner
  - python39-ansible-runner
  - ansible-builder
  - ansible-navigator
  - libguestfs-tools
builder_repos:
  - ansible-2.9-for-rhel-8-x86_64-rpms
  - ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - rhel-8-for-x86_64-baseos-rpms']
builder_github: "https://github.com/syspimp/aap-repo"
builder_privatesshkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66343264633433653431313261323762373366316264326636366138353363653061613062346435
          3632643535653961393634353465343830376130653032380a316338383361666465363536383962
          35383264326662623465663831623133333531623164663663303763613539613365613234303633
          3864393537656666620a643866303831313431346634343666663834383035633835316337326331
          34636430623532383234336237333336363165353863623633316333663638306533613062393535
          30636539626234613336346436303264363966323435653431663663653561326337643266393165
          37326134306631623532303737396435636164666435663131623664396338336230386136373331
          31383331393435326539393365383438643737353336333661393136326232623131353466343965
          62666564396264623664663130353763353566626131323631633833643937383766383431346264
          36353464666634653234373366356532323133643635633366653836313035396466386333303935
          32623935633839373939653535393131633631633939393630633233316231663134656264336330
          34356131396337663131333532633837656132616437666362336236393063306466373734396632
          37616335613633303665303831613936393265613139333462313236356361626131653334303066
          62616262656236393133313065373964366462333132323736356132616430326338323862653932
          66636261386238653866386137656537326535666361643730313563643631316331353330396634
          37326133303165353032666137303233363737633530313137643064353166663766376334326336
          64353831623432663138633934393334316239363336626463303530643966363135353835313830
          31663732643838376339643533316437313031383738346161336365316365303366396166383566
          32353835633134613831663663313138363864306636393733313839313065393961363334346439
          35663331656635653432616138323735626130303330373463623738393132656261313136373837
          63313730653637363037313537653936363735396564663061616531666431623735343965633036
          31303038636233343263306235636662633631396431393266323332316137616366663561633634
          33366338303563333136393935303339653063303535386537346166666434366464643730393135
          61323136396134376264333838326666633764613531373838353962663363616339323864346539
          32633531303634386232333631356236663662623561376662613565376638613963643261656630
          37656537333735306230643065643338396665346231303036303430613964613062393230613366
          34316634366232396235386439353362313931306665633863393636643761353132393631666539
          31393439623664386539323133326437666432366131353632313132383362303137396261663739
          39633535343562653835363831306337396266313234396161343164623138663563663766346630
          62663464646233663037636563303266626531643262663166366666393036666563373536366438
          64346230383066313639323665353164653238316537663539386564636638643061303333323336
          35666134613439383531623866393532393036666230323864353936613261633032313061643531
          30323035303237373230623861346565373465316131316330633836376533396561343664376538
          65336662643630613430346561366365363764633836643765633138666233356637636362343461
          61303638333832653933666133353731643238306466386336306139616363363662623530633832
          34663332626131313063393262363235643166383930356230303734633635363962356131376131
          63613366653030383830626235363465393830633837363366346561663363356332303434613163
          39383765353861306665346134366262383739363134363634663332386462363436383934333663
          35636534633534386339356137386235653432633163663038383631643738373230366237326262
          64386130643036353039616132623039646438326566643334376462386136356435383739653538
          38326662383633396361343835333639396163356135333666656465613330656431356465336133
          65646539383333303234386233643666613630363661383331623637636533376331663561386633
          62653163663331643133396135373936363637393863386233313332623264353431306437393438
          36363665363537616635653864306436626330663337356339333264653539623236323837663534
          63626430323838663933633966346131373730623638646337306263396434316530343663646231
          32643733343030666235343161623430313662336532373539306234646136633533303639333163
          36383533346564386161663835326638363935396534376436623262663735306332303732316365
          33376363363663636462376663356464326137626335313834386139363361336665343538613365
          61333962343031363936616163333731386533366331346364363832626161383561383766393034
          61313262306363326338313530396466346264353438386664656133663539353165386634626237
          33343765396638356536636633386262313837343931313934333536323833386565353036616130
          66316165316361313236336634343935373439663239626639313533666339643530373131363636
          66626566316339376530333662613839653861656338336236373864333866643939636365613863
          63663430616461376332643035303131353137643865643031343961313731363837313237363066
          34303161376166363235396435633037656164363731343761663361663865326136373738333030
          38636333376464363161373830656234306566663530363463373835353839663937636464636163
          63646233396338336635393836366362633338636664663365313762343232653430363133626464
          66386130653461343131633738656638303066333231656162633464653962343963646232633562
          64366637323431336461623133393838356430626436333834646238366434393034356534663639
          35353434323532613831363061336139346562653037323237643963363764653830636333366231
          64373565383536333265613461346538343136326133643264336366326666643365363233303566
          38653664396264346237613638386534353230343362623439633235383531306232653730626366
          66393736343432303364326635303137383839633636323038306163336136666663663331323863
          66313939353234623466383866366238366561383636373033393234623864303066653562313264
          35333031313731623535333664663462656661643466633634366131346564333963633961346365
          66333630343936653936393435366264356665306634376562363638383633623335373836663236
          36653630636139336439666561366566323031343732373765623565663433303430326362373461
          61333339316562613532336432353630663565336365666264653038613931386563633639333532
          30373766623732646330633631386430326664356363633236303330316632633131616666316163
          66396435376164396231303664363632656437333632623438326538633563393562313437323038
          38313266633430663537383733383731366433646131643634656435333738333761356662383039
          61346437336635633031343938326339613439373161633234343466643434353166363033306235
          66376533383839373233323235626637393838323434356333363962323835343937316362323731
          64666633626566643239333631356661316666333537396332336334383961313737656534373264
          30346534366331386365333165623831306165663464363032666462303037343061323139336433
          32353339373861633464656131373832373939636432316632303562353430663437616461343163
          33363532646239323762633466613066373965623838663738313337336130343861323562306434
          66383831373561316135363862333634656132636333386431326364353666316438666633306537
          64346533396561326530616631353466383232303037623263363330626465303261626637613364
          33343839633631613062326561353232626331643562613035303435636361613834336262323530
          37373437343833313734313932646431373962313665333764336534666635646166633164643637
          63656634343864633137646366323863626430366236633664356562353964656433306630626263
          39633838656563313966663438386136336639656434363837646262363237336161336163616362
          39663063313238323137616638343965376566343162633162663937393962653161656536613236
          39653763636566366562623962326164336337636631653064326333666633303936643233663839
          62633465356133383530396135333735633634393830623335653663643661333962303131373366
          64616430663366363332323730343036326331393339316438373232633763623562303435353638
          31383734633439363361613264613661633330656539623432653936656533323137303332626334
          37366438623633366239353131663563653834653364323831393233343139336463343731386166
          37633935346430616238306137323937626531363130386235653762313635613563653361396137
          37383262363233313638663632643831613431323835663565353262666337323062336464363337
          39303362343661316161623234303662303531366439633361656338363965373866383263616365
          31343232333661383664653466666564303234363038356232626161643962393835616466646136
          39363536633836613333636632633366623765343033393638316365643165383832623562353264
          63646436353666666238643536386336646339383330383338616337633237396362663436376163
          37366138373338373233366664366164333664336365333663613630346233313466343635353438
          37376337336432653364316162636133323136393138363033323961656331366566623666633165
          34333639383330633164656162653736366337626565616565343130636262653766343739376236
          34653033643134353535346337656538643230393963353731366437383539663733626531336136
          65366530353863323737633536383162333036306330373666343164643630616533343931343565
          65346233636463653533666336353939636161376164366332363562353865333931373730623564
          62306665393830323061336539633432646666663136376337613064613562303434623361376232
          36393937313939626532623939316465343062666233373430323739656438633538363236643361
          65396436316138343834623430616663666436653233333966663561623835636665613437336662
          39613939636136323665613463313761333964626632633034643537316266636436333834313434
          63363039633230376463396333373961363364636330303539623365313937613230653964613735
          62626337353139613038656332623061303738396638633031393061386636666332396637363932
          64363461653738353236343163313265363766663363306665633066303334633536666537666361
          65623264313239366135316538383539303064393832613637383731336533366365333661326537
          66393264383064313238363931363765363462393365646564353630623437316434363763383562
          37643430303639303132613263333765613637303835303038333438376666323162636161336238
          34386430396638376135383363313433653062613739303534373134383236376264386165613437
          32343162353963376239623138633037386463616434356537656332333164356533373537333137
          65376639633230666232636432346662383237353662363132313932366165333232343861633662
          64336663633139366463616365323764396531643035663932313262336430313564623635343834
          64336661316333626531343631613339633237653330333464353664353164633136613536393731
          34336264643039646361336433643863643237373166383833643933613964363931323266623536
          62363837343532643937383361353063333834396261366662323235373534306562323765303539
          33666362383530383435396164666564663234393331333564653165633664316262326661653231
          36343839666131666363363265646436373531393666313030623337303634653333633535363963
          32656530383539643330633831653430353634616365356464326162633331346165393531303334
          36356435386135323139633833393861653930326132303661333866646330613431313537376663
          35313331313166613663633064376237356637343666323662336337623135636131636537326361
          62303330363831313662303266666463663565663134303834383634373139663862346463353866
          64326235323038636539653335333030336232623862396231323265303663323664643862663962
          39616362653632666637613837326633316637373663393765376664656564633266366533323631
          35663336303361366430613135633334636563323666653966386232343138623766333031353863
          66303334623835366233633666343936656133396130663136376166363166346635373233303865
          31663063373933373261316135353832333934643339656666386335313132363462613634623565
          63656231386431396563323130326637663362383266386139346538386633323731373931323063
          63656335653639393834363739646435383232623537636236373666616165313862656463353334
          64383131663738343466386434323865373537393166653464643331663335646562356163303236
          39323666333837373831663762643165363531323437663865383330316439316662303235323865
          30396134393436343930353861363439313932326630393666303039613232633666616161343861
          33343638323065623736626435643430616166666362376334353631646334336163626437326232
          39646232383465303762386232303538356165303439396538633635393934343763343861353364
          61666635383339366364616366616164323661343666656536356130343036613733323561326363
          36656261343563356236623635353333306235316631343632643764346138306437653730633461
          34383661646239666635643530313337613133656634333334306639343862613931393034643663
          34656564666264653735303531656539346165303139323962353637333130323433316166303264
          37626131633732363364333532353736623939366630396537373764383265336365346161303933
          63663965383066353063313938633236376435633634303966653233386530393864353937343861
          33666530613431613730613561353233343065323537333135633638633764396634393930376136
          32353232663665383362376165373532326463323561666636666631646632313662386261363430
          31613163633933623936303361626533363161323232383564613962653533343936346638383261
          61393263326636666665336662633063653366303337666637386462373865383637373839353561
          64376465336566363237386162313531333063633265363862386661326461663831653036663663
          38366232323065383830653366623033643030363435346332326332643662363763383931326233
          31316239303862303266386130346362646631636233353362643562636638633263656562326634
          35643963376564323164616633653831313139376631313136316461663332363366323864653035
          36386361386262353035373264316462643032376163373761643033646238373462383463393866
          35373831323462333136313835333831653666623336623562336537373461663936653161373166
          37373536383133626261633961376366393239336162393832396437346561343762646561633239
          66353562353066633937356237306462363032333531353438336135303264363430613432373066
          66366535343432383265363361376465363032356563343465343931613262393862313263343139
          35366532366230376533313532303965343034383362303262333732353736373533393666323235
          65396364353532323333613139313636316435373035626131643534326264316137303565373565
          65656133306163613335303533653630393964366138623464643065646566303535653135393963
          38336332373664666438646130373831656132373439396365656266316264393838353130333430
          31623031613036373964366264633131393234633830633639663832343133613163303532653231
          35633165323664376434646433356264323866646637396136663266366463373830623438393961
          30663165353337383466393262393735306565346333313737623661393062326561313062363363
          34323236363237626563316632396662336335393733653838633630323534353461643931646664
          38303564303433633032323734366635313933386334373232346337353461613631646439663230
          38396638326436343465666366656132653430633063646130336539623933383734663465316463
          61326363316135616331356365333634333039326632353031323230373366383231396266383737
          62336366356232613239623535356463346635646639613433386432636636313931633631343861
          30366432666536366631393031633930636563353233616139396162373735313835306231363339
          37303038346231623038623339383163303238316235613937373737613434663763303235316631
          65333732643365633463643962303135336331636331383037336430623939646361623335363131
          39303563333236353336636266643365636332646233313434626237616665393764333334303262
          66646138613831626631353935656132313331306531613737343230356535653037356134343232
          31356638656162626136316666613063663132346334386538303836343161336330
