---
## https://github.com/ansible/workshops/tree/devel/provisioner#requirements
## don't forget to go to https://access.redhat.com/management/subscription_allocations to create a manifest.zip and place in the files directory
workshop:
  name: demo-workshop
  how_many_students: 2
  type: windows
  dns_zone: prod.maskedadmins.com
  default_password: ansible123
  # do you want to install tower on the system?
  towerinstall: yes
  # go to https://access.redhat.com/terms-based-registry/#/accounts to create a service account
  redhat_svc_account: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62666661333631386333383633333237356162656332333835636563363265613963353136663032
          6430616365336561623964643630343162626133393335370a353261663933306132393239303462
          38373665626433666335306634616133316238656134633630316135613735313533356638353139
          6430373435653061340a346365326633333335366663633039336436383964376337346364663337
          38643032336337656334663733373739326633306237396533613839656162313261

  redhat_svc_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32326335643031316164346363323064623134663632303937613837613961633436303864373639
          6561366664373638393864313564353132313762393734380a303563666633323937643937326136
          35623362303462643037323264666436393762353839623763613165333165386633393366643931
          3432336133643762370a343739636530326336633438656238366439326134366163663732666230
          35626133363439613636643630653639306633643234653966656163636238353730373336343931
          30383837366230336133326166313962376234323537346461356535383239653937313037363338
          30313738366538643331373234313633376263363732323234353161346433636563613732353435
          65366133343037656635316534353237663832373131323263396236303631393065666462313631
          33636639653738393866646636616264353965363961346566333166363033633237666432333530
          61383132313663373761303730303437353662376237346634613264336531653264373262633166
          34663932356230323466373030353063333761356632343866343739626536656138353736613063
          36656438303335323438373530633061306437653032363335653734386662643036306533373834
          62303531306431303866363865343830393530316431363936626562306463386463366534613332
          33643734303132663133653938626463323666336439656463383337623461663961613566353436
          36616635323438363366396335656636373463643937376666343564636234353563666633636161
          35313865313232343563646262343430376130623633626565376661653562313730366662303063
          32343430363536356333643636663335643866623063313930386436613864383833643666303634
          30626432656131383161633136303661306436653337313837633464623230383237323132383865
          62313231313135613961386232663534623939393466303739356665643138333263346166353162
          39613931663135373033343230616238646661393363396663303731323836613336656561383037
          65323432646532383332303063323737656530613132376136626135623934633166326566363136
          62626439636364623638616435326631666333356138643465316431323464633039616332643563
          64333839633765346263616162343532626639393035646262386233336138333762343632333130
          66313263663734653165383363333039333066363964336237323539333764316565313233383632
          62643136353431616337323364383063353939623832633639326438333364316535366231633133
          34336538643635663432623332366630383566316138626262623239646162376262633434613536
          34373731323262636232333035613062363235393039663233616232333235626264346465643066
          30373162336237346534626237303862663930393436636537323633633434663930643739353661
          39366235383566353738383534386633626138333738633663303664333665643561633136613232
          62656530323634336265383934616661376231363863303739313838356631653638356431653233
          31633639656239613633666131323231623266303965613964313830303164306563336661353938
          64306262383231303938346236663462383738373161353335613566653063333133653237653265
          36333034636562623364643262386363383137346335363135393062663933386439313433613539
          62316539656562316361333761326632343138663535353866646530313632386536353938356332
          38343531633065366437613163623938646664623331643663303834646138393862363736303061
          34396661643039643632376465376439613632653364363832386462393936316436616362633063
          66363035353535623566613235323330633866323935353836363431646330643339656561373730
          66393332643332653038303732363834396261353535653737636436326236656166383839303433
          35333565393732656262336338386638306536613837633535326635303061336462323834316335
          39366139633638653038393165326262373738383031323532386637326439623535356664646363
          31623233336631356436623639366236396663333536373262613839333463333735666431336463
          6338316436353961366666646334363663353335393761613530

  # for redhat cdn api access https://access.redhat.com/management/api
  redhat_offline_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39663030636536623330643563326634303632623763316333663431613333383939356462393866
          3161323332656330613663666238303265393832613638330a366438623234653039643030353363
          37393565363233383065653964636635393832366135336433356437366636666530333337613562
          6530376135373931630a366435326266306261383538313762313061343936656134316464653163
          30386333353732656437393238616462353234616333646437346533613762363465343263656665
          62626531643536316465626661313835366231653239303038616162663035356365623439623530
          34353433363864646139373538646233316630633264623564323732656134306537626630383164
          65303666333661633930383565333538613266396365376566653830663933366333333362653237
          62626539623736346633633036383332343232396236373138623438356366646630373366333536
          34373030373733613836303434633236336665383061383332623563393239646662343530623937
          38373133353337343563306238383162616565636432336339636136383334663962616231333463
          61393431363833646634343366383964326363626130376362333233313531373435353030333566
          38333561333237306261653637313234313639626466643733626666633065373935326634376565
          35393637653665343961396566626465636466653833353063343033626134336266626565373735
          36643037396363656135353762303838353363633537626237633462346164346135373665373262
          64303661666135366663303935356130626365643834373261666163616432623666356666613562
          32393565373137333161303738383138313031623266663734353062333664336434383537343731
          38393033666237663462393034373265383861333861386331376638323465316130383538363238
          62363862363639333262666363663637663363383666316665303261666561326639643266636433
          64653032623463346564333362343335663338363032373933646261386566663639383135666139
          64373139376438613538653737323364363562313737363835633933616534346236353166363564
          30633337653465353137373764613335653733653262636233333639616365666163336334373533
          33323834623664646365653631303930306135386464376533343338306537303638306265306261
          39396432313935346666666262333431313862303734626631373466326630623738626433343039
          34633664376364373635663938366234656238303562326464333761623033376130336665383939
          32333132373035353438373236363766393466613961303463613934363937366439356565653731
          63633837666637313936636139323035653839623333343361393339666466363531656339303661
          36646131386361326265353336336566626463396466613733653131643165646362626563653666
          65373232643333313338376438346162326561663035376462663533323161353962626133376630
          30636562643739656432633036323164666363386666373131303930373938666533396266363666
          65346635633766323563316633343461613566353966666331303430616233363964393130633034
          36343165666234646465373663626234613437623066386134346632313465363435333437613464
          62333331633861656636376264386162343230623935646536316536313661376631383634333439
          37366238376136313236636563356434626633356336336262303831366437363262613336383934
          34306531346362376132396662376638306139386432343464356434653261363732313039386263
          65333333383631326666

workshop_deps:
  pipmods: 
  - boto
  - boto3
  - netaddr
  - passlib
  - pywinrm
  - requests
  - requests-credssp
#  - ansible-tower-cli
  - https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz
  rpms:
  - git
  - ansible
  - python3-pip
