---
#tower_tarball_location: http://ec2-54-234-230-108.compute-1.amazonaws.com/tower/ansible-tower-setup-latest.tar.gz
tower_pkgs: ['python2-boto','python2-pip','python-heatclient','python-openstackclient','python2-shade','python-devel']
tower_tarball_location: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
restore_backup: "no"
backup_file_src: "/opt/ansible-tower-setup-3.2.3/tower-backup-latest.tar.gz"
backup_file_dest: "/opt/tower-backup-latest.tar.gz"
cfme_user: "admin"
cfme_pass: "smartvm"
cfme_creds: "admin:smartvm"
cfme_type: "ManageIQ::Providers::AnsibleTower::Provider"
cfme_server: "cloudforms.dev.maskedadmins.com"
cfme_project: redhat-lab
tower_name: "Ansible Tower"
tower_server: "tower.prod.maskedadmins.com"
tower_security: ssl
tower_user: "admin"
tower_pass: "ansible"
openstack_inventory_domain: "prod.maskedadmins.com"
