snmpd:
  sysname: "{{ inventory_hostname }}"
  sysdescr: "{{ ansible_local['roles']['default']['role']  | default('No defined role')}}"
  syscontact: "Powered by Ansible"
  syslocation: "Somewhere ..."
  rocommunity: "TFOUNDRO"
