---
sat6_org: "Redhat_Lab"
sat6_env: "production"
sat6_loc: "ESXI_TFOUND"
#sat6_loc: "Private_Cloud"
sat6_hostgroup: "RHEL_{{ ansible_distribution_major_version }}_x86_64_Hostgroup for {{ dns_domain }}"
sat6:
  user: "admin"
  pass: "CHANGEPASS"
  org: "{{ sat6_org }}"
  hostgroup: "{{ sat6_hostgroup }}"
  location: "{{ sat6_loc }}"
  environment: "{{ sat6_env }}"
  activation_key: "{{ sat6_org }}-{{ sat6_env }}-key"
  lb_fqdn: "capsule-lb.{{ dns_domain }}"
